version: '3'
services:
# MYSQL DB
  mysql:
    image: mysql:8.0.17
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=config
      - MYSQL_USER=config
      - MYSQL_PASSWORD=config
      - MYSQL_DATABASE=config
    ports:
      - "3306:3306"

# Redis
#  master:
#    image: redis:5.0.5
#  slave:
#    image: redis:5.0.5
#    command: redis-server --slaveof redis-master 6379
#    links:
#      - master:redis-master
#  sentinel:
#    build:
#      context: .
#      dockerfile: ./compose/local/sentinel/Dockerfile
#    environment:
#      - SENTINEL_DOWN_AFTER=5000
#      - SENTINEL_FAILOVER=5000
#    links:
#      - master:redis-master
#      - slave

# Django
  django: &django
    restart: always
    container_name: django
    hostname: django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: portifolio_local_django
    environment:
      - MYSQL_ROOT_PASSWORD=config
      - MYSQL_USER=config
      - MYSQL_PASSWORD=config
      - MYSQL_DATABASE=config
    links:
      - mysql:mysql
#      - master
#      - slave
#      - sentinel
    volumes:
      - .:/usr/src/app/
    expose:
      - "443"
      - "8000"
    ports:
      - "2005:22"
    command: bash -c "source compose/local/startup.sh"
    depends_on:
#      - master
#      - slave
#      - sentinel
      - mysql

# Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
      - ./compose/local/nginx:/etc/nginx/conf.d
    depends_on:
      - django

volumes:
  redis_data:
